config/routes.rb
Wewaitforyouin::Application.routes.draw do
  root to: 'home#index'

  get '/auth/:provider/callback', to: 'authentications#create'

  resource :home, only: [ :index ], path: '/', controller: 'home' do
    get :search
    post :find
  end

  resources :cities, only: [ :show ], path: '/' do
    constraints(Subdomain) do
      get '/' => 'proposals#show'
    end
    resources :proposals, only: [ :show ], path: '/proposals' do
      resources :votes, only: [ :new ]
    end
  end
  resources :cities, excepy: [ :edit, :update, :show, :new, :create, :index, :destroy ] do
    get 'search', on: :collection
  end
  resources :proposals, only: [ :create ]
  resources :artists, only: [ :create ] do
    get 'search', on: :collection
  end

  scope :admin do
    resources :cities, only: [ :edit, :update, :show ]
    resources :artists, only: [ :edit, :update, :show ]
  end

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :profile_cities, as: :profile, inverse_of: :profile, dependent: :destroy
  has_many :cities, through: :profile_cities

  has_many :profile_proposals, as: :profile, inverse_of: :profile, dependent: :destroy
  has_many :proposals, through: :profile_proposals

  acts_as_url :name, url_attribute: :permalink

  # belongs_to :proposal

  validates :name, uniqueness: true, presence: true


  has_attached_file :cover,
    :default_url => "/missing.png",
    path: ':rails_root/public/uploads/artist-covers/:id.:style.png',
    url: '/uploads/artist-covers/:id.:style.png'

  def to_param
    permalink
  end
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base

  has_many :votes, dependent: :destroy

  has_attached_file :avatar, :styles => { :medium => "300x300#", :thumb => "100x100#" },
    :default_url => "missing.jpeg",
    path: ':rails_root/public/uploads/logos/:id.:style.png',
    url: '/uploads/logos/:id.:style.png'


  before_create :generate_auth_token

  def self.create_from_omniauth(omniauth)
    self.new.tap do |authentication|
      authentication.provider = omniauth['provider']
      authentication.uid = omniauth['uid']
      authentication.name = omniauth['info']['name']
      authentication.avatar = omniauth['info']['image']
      authentication.facebook_city = omniauth['info']['location']

      authentication.token = omniauth['credentials']['token']
      authentication.secret = omniauth['credentials']['secret']

      authentication.save
    end
  end

  def generate_auth_token
    if self.auth_token.blank?
      self.auth_token = SecureRandom.hex(12)
      generate_auth_token if Authentication.where(auth_token: self.auth_token).present?
    end
  end


end

app/models/city.rb
class City < ActiveRecord::Base

  has_many :profile_cities, inverse_of: :city, dependent: :destroy
  has_many :artists, through: :profile_cities, source: :profile, source_type: 'Artist'

  has_many :proposals

  belongs_to :country

  acts_as_url :name, url_attribute: :permalink

  has_attached_file :cover,
    :default_url => "/missing.png",
    path: ':rails_root/public/uploads/city-covers/:id.:style.png',
    url: '/uploads/city-covers/:id.:style.png'

  def to_param
    permalink
  end

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :cities
end

app/models/profile_city.rb
class ProfileCity < ActiveRecord::Base
  belongs_to :city
  belongs_to :profile, polymorphic: true

end

app/models/profile_proposal.rb
class ProfileProposal < ActiveRecord::Base
  belongs_to :proposal
  belongs_to :profile, polymorphic: true

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  attr_accessor :artist_id
  # has_one :artist
  has_many :votes, dependent: :destroy
  has_many :voted_users, through: :votes, source: :authentication

  has_one :profile_proposal, inverse_of: :proposal, dependent: :destroy
  has_one :artist, through: :profile_proposal, source: :profile, source_type: 'Artist'

  acts_as_url :artist_name, url_attribute: :permalink

  belongs_to :city

  # validates :artist_id, presence: true

  def artist_name
    artist.name
  end

  def to_param
    permalink
  end

  def find_or_create

  end


end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :proposal, counter_cache: true

  belongs_to :authentication # as User
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :get_artist, only: [ :show, :edit, :update ]


  def show

  end

  def edit

  end

  def update
    if @artist.update(artist_params)
      redirect_to @artist
    else
      render action: :edit
    end
  end

  def search
    @artist = Artist.order(name: :asc).where('LOWER(name) LIKE ?', "%#{params[:term].downcase}%").limit(20)
    render json: { results: @artist.map { |object| { id: object.id, text: object.name } } }
  end

  private

    def get_artist
      value = request.subdomain.present? ? request.subdomain : params[:id]
      @artist = Artist.where(permalink: value.downcase).first
    end

    def artist_params
      params.require(:artist).permit(:name, :cover)
    end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :get_city, only: [ :show, :edit, :update ]


  def show
    @proposals = @city.proposals.order(votes_count: :desc)
  end

  def edit
  end

  def update
    if @city.update(city_params)
      redirect_to @city
    else
      render action: :edit
    end
  end

  def search
    @city = City.order(name: :asc).where('LOWER(name) LIKE ?', "%#{params[:term].downcase}%").limit(20)
    render json: { results: @city.map { |object| { id: object.id, text: object.name } } }
  end

  private

    def get_city
      @city = City.where(permalink: params[:id].downcase).first
    end


    def city_params
      params.require(:city).permit(:name, :cover)
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'landing'

  def index
    p request.subdomain
    @proposal = Proposal.new( city_id: @current_city )
  end

  def search

  end

  def find
    objects = Artist.order(name: :asc).where('LOWER(name) LIKE ? OR LOWER(permalink) LIKE ?', "%#{params[:search][:term].downcase.strip}%", "%#{params[:search][:term].downcase.strip}%").limit(20)
    cities = City.order(name: :asc).where('LOWER(name) LIKE ? OR LOWER(permalink) LIKE ?', "%#{params[:search][:term].downcase.strip}%", "%#{params[:search][:term].downcase.strip}%").limit(20)
    objects += cities
    render json: { results: objects.map { |object| { permalink: object.permalink, text: object.name, cover: object.cover.url } } }
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :load_proposal, only: [ :new ]

  def new
    session[:proposal_id] = @proposal.id
    redirect_to '/auth/facebook'
  end

  private

    def load_proposal
      @proposal = Proposal.where(permalink: params[:proposal_id]).first
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def set_menu_items(*items)
    html = ""
    items.each do |link|
      html << "<li> #{link_to( link[0], link[1] )} </li>"
    end
    @menu_items = html
  end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def artist_cover_photo_for(artist)
    return artist.cover.url if artist.cover.present?
    return image_url("backgrounds/artists/artist#{rand(3)+1}.jpg")
  end

end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
  def city_cover_photo_for(city)
    return city.cover.url if city.cover.present?
    return image_url("cities/#{city.permalink}/cover#{rand(1)+1}.jpg")
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper

  def can_vote(proposal = nil)

  end

end

app/helpers/url_helper.rb
module UrlHelper

  def with_subdomain(subdomain)
    subdomain = (subdomain || "")
    subdomain += "." unless subdomain.empty?
    [subdomain, request.domain, request.port_string].join
  end

  def url_for(options = nil)
    if options.kind_of?(Hash) && options.has_key?(:subdomain)
      options[:host] = with_subdomain(options.delete(:subdomain))
    end
    super
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    / meta name="title" content="#{t('page_names.' + active_menu.to_s)}"
    / meta name="description" content="Wire.as is a startup ecosystem that provides information everybody needs to find investments, startups, news, and partnerships."
    title We Wait for you IN

    / link rel="shortcut icon" href="#{image_path 'icons/favicon.png'}"
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'

    = csrf_meta_tags

  body
    = render 'shared/menu'

    = yield

    = yield :javascript

app/views/layouts/landing.html.slim
doctype html
html
  head
    meta charset="utf-8"
    / meta name="title" content="#{t('page_names.' + active_menu.to_s)}"
    / meta name="description" content="Wire.as is a startup ecosystem that provides information everybody needs to find investments, startups, news, and partnerships."
    title We Wait for you IN

    / link rel="shortcut icon" href="#{image_path 'icons/favicon.png'}"
    = stylesheet_link_tag 'landing', media: 'all'
    = javascript_include_tag 'application'

    = csrf_meta_tags

  body
    = render 'shared/menu'

    = yield

    = yield :javascript

    / = render 'shared/ga' if Rails.env.production?

app/views/shared/_menu.html.slim
a#menu-toggle.btn.btn-primary.btn-lg.toggle href="#"
  i.fa.fa-bars
div#sidebar-wrapper
  ul.sidebar-nav
    a#menu-close.btn.btn-default.btn-lg.pull-right.toggle href="#"
      i.fa.fa-times
    li.sidebar-brand
      = link_to "Home", '#'
    li
      = link_to search_home_url(subdomain: 'www') do
        span Search
        i.fa.fa-search

    = @menu_items.html_safe

javascript:
  $("#menu-close").click(function(e) {
    e.preventDefault();
    $("#sidebar-wrapper").toggleClass("active");
  });
  $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#sidebar-wrapper").toggleClass("active");
  });

  $(function() {


      $('a[href*=#]:not([href=#])').click(function() {
          if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
              if (target.length) {
                  $('html,body').animate({
                      scrollTop: target.offset().top
                  }, 1000);
                  return false;
              }
          }
      });
  });