config/routes.rb
Wewaitforyouin::Application.routes.draw do
  root to: 'home#index'

  get '/auth/:provider/callback', to: 'authentications#create'

  resource :home, only: [ :index ], path: '/', controller: 'home' do
    get :search
    post :find
  end

  resources :cities, only: [ :show ], path: '/' do
    constraints(Subdomain) do
      get '/' => 'proposals#show'
    end
    resources :proposals, only: [ :show ], path: '/proposals' do
      resources :votes, only: [ :new ]
    end
  end
  resources :cities, excepy: [ :edit, :update, :show, :new, :create, :index, :destroy ] do
    get 'search', on: :collection
  end
  resources :proposals, only: [ :create ]
  resources :artists, only: [ :create ] do
    get 'search', on: :collection
  end

  scope :admin do
    resources :cities, only: [ :edit, :update, :show ]
    resources :artists, only: [ :edit, :update, :show ]
  end

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  attr_accessor :artist_id
  # has_one :artist
  has_many :votes, dependent: :destroy
  has_many :voted_users, through: :votes, source: :authentication

  has_one :profile_proposal, inverse_of: :proposal, dependent: :destroy
  has_one :artist, through: :profile_proposal, source: :profile, source_type: 'Artist'

  acts_as_url :artist_name, url_attribute: :permalink

  belongs_to :city

  # validates :artist_id, presence: true

  def artist_name
    artist.name
  end

  def to_param
    permalink
  end

  def find_or_create

  end


end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :redirect_if_city_missing, except: [ :create ]
  before_action :get_proposal, only: [ :show ]

  def show
    @votes = @proposal.votes
  end

  def create
    #TODO rebuild!
    @porposal = Proposal.where(city_id: proposals_params[:city_id])
  end



  private

    def redirect_if_city_missing
      unless params[:city_id].present?
        redirect_to root_path(subdomain: false)
      end
    end

    def get_proposal
      @proposal = City.where(permalink: params[:city_id].to_url).first.proposals.where(permalink: request.subdomain).first
    end

    def proposals_params
      params.require(:proposal).permit :city_id, :artist_id
    end

end

app/helpers/proposals_helper.rb
module ProposalsHelper

  def can_vote(proposal = nil)

  end

end

app/views/proposals/_form.html.slim
= simple_form_for proposal, url: proposals_path, html: { class: 'form-inline new-proposal'} do |form|
  = form.input :artist_id, as: :string, input_html: { class: 'select2-input', 'data-url' => search_artists_path }, label: false, wrapper_class: 'form-group', class: 'form-control', placeholder: "#{t 'forms.proposals.artist.placeholder'}"
  = form.input :city_id, as: :string, input_html: { class: 'select2-input', 'data-url' => search_cities_path  }, label: false, wrapper_class: 'form-group', class: 'form-control', placeholder: "#{t 'forms.proposals.city.placeholder'}"
  = form.submit 'Create', class: 'btn btn-success'

app/views/proposals/show.html.slim
- set_menu_items( ['aabb', 'bbaa'] )
section.page.proposal-profile
  header.text-center style="background-image: url(#{artist_cover_photo_for @proposal.artist})"
    h1
      =<> @proposal.artist.name
      br
      | in
      =< @proposal.city.name
      / - can_vote? @proposal
      br
      = link_to new_city_proposal_vote_path( @proposal.city, @proposal ), class: 'btn btn-success' do
        i.fa.fa-plus-square-o &nbsp
        = "Vote"

  section.proposals
    ul.container
      - @votes.each do |vote|
        li
          = image_tag vote.authentication.avatar.url, alt: vote.authentication.name