config/routes.rb
Wewaitforyouin::Application.routes.draw do
  root to: 'home#index'

  get '/auth/:provider/callback', to: 'authentications#create'

  resource :home, only: [ :index ], path: '/', controller: 'home' do
    get :search
    post :find
  end

  resources :cities, only: [ :show ], path: '/' do
    constraints(Subdomain) do
      get '/' => 'proposals#show'
    end
    resources :proposals, only: [ :show ], path: '/proposals' do
      resources :votes, only: [ :new ]
    end
  end
  resources :cities, excepy: [ :edit, :update, :show, :new, :create, :index, :destroy ] do
    get 'search', on: :collection
  end
  resources :proposals, only: [ :create ]
  resources :artists, only: [ :create ] do
    get 'search', on: :collection
  end

  scope :admin do
    resources :cities, only: [ :edit, :update, :show ]
    resources :artists, only: [ :edit, :update, :show ]
  end

end

app/models/city.rb
class City < ActiveRecord::Base

  has_many :profile_cities, inverse_of: :city, dependent: :destroy
  has_many :artists, through: :profile_cities, source: :profile, source_type: 'Artist'

  has_many :proposals

  belongs_to :country

  acts_as_url :name, url_attribute: :permalink

  has_attached_file :cover,
    :default_url => "/missing.png",
    path: ':rails_root/public/uploads/city-covers/:id.:style.png',
    url: '/uploads/city-covers/:id.:style.png'

  def to_param
    permalink
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :get_city, only: [ :show, :edit, :update ]


  def show
    @proposals = @city.proposals.order(votes_count: :desc)
  end

  def edit
  end

  def update
    if @city.update(city_params)
      redirect_to @city
    else
      render action: :edit
    end
  end

  def search
    @city = City.order(name: :asc).where('LOWER(name) LIKE ?', "%#{params[:term].downcase}%").limit(20)
    render json: { results: @city.map { |object| { id: object.id, text: object.name } } }
  end

  private

    def get_city
      @city = City.where(permalink: params[:id].downcase).first
    end


    def city_params
      params.require(:city).permit(:name, :cover)
    end

end

app/helpers/cities_helper.rb
module CitiesHelper
  def city_cover_photo_for(city)
    return city.cover.url if city.cover.present?
    return image_url("cities/#{city.permalink}/cover#{rand(1)+1}.jpg")
  end
end

app/views/cities/_form.html.slim
= simple_form_for city, url: "/admin/cities/#{city.permalink}", method: 'put' do |form|
  = form.input :name
  = form.input :cover
  = form.submit :update

app/views/cities/edit.html.slim
= render 'form', city: @city

app/views/cities/show.html.slim
/ a#menu-toggle.btn.btn-primary.btn-lg.toggle href="#"
/   i.fa.fa-bars
/ div#sidebar-wrapper
/   ul.sidebar-nav
/     a#menu-close.btn.btn-default.btn-lg.pull-right.toggle href="#"
/       i.fa.fa-times
/     li.sidebar-brand
/       = link_to "#{@city.name}", '#'
/     li
/       a href="#top"  New
/     li
/       a href="#about"  Most Popular
/     li
/       a href="#services"  Find


section.page.city-profile
  header.text-center style="background-image: url(#{city_cover_photo_for @city})"
    h1
      = @city.name
    h5
      => @city.proposals.count
      | Proposals

  / section.proposals
  /   ul.container
  /     - @proposals.each do |proposal|
  /       li.col-xs-12.flip-container
  /         div.flipper
  /           div.front style="background-image: url('#{artist_cover_photo_for proposal.artist}')"
  /             h3 = proposal.artist.name
  /           = link_to city_proposal_path(proposal.city, proposal), class: 'back' do
  /             h2
  /               = "#{proposal.votes_count} VOTES COUNT"
  /             - proposal.votes.limit(300).each do |vote|
  /               = image_tag vote.authentication.avatar.url